name: Push to Github Container Registry

on:
  release:
    types: [released]
  issue_comment:
    types: [created]
env:
  IMAGE_NAME: hello-world-docker-action

jobs:
  push:
    runs-on: ubuntu-latest
    if: (github.event.issue.pull_request && contains(github.event.comment.body, 'container push')) || github.event.release
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout Pull Request
        if: github.event.issue
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build . \
          --file Dockerfile \
          --tag "$IMAGE_NAME" \
          --label org.opencontainers.image.source=https://github.com/${{ github.repository }}
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_ID=ghcr.io/elipinska/"$IMAGE_NAME"

          # For issue comments, use a short sha as the version
          if [ "${{ github.event.issue.number }}" ]
          then
            VERSION="$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} -q .head.sha | cut -c-7)"
          fi

          # For tagged releases, use the version tag instead
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]
          then
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          fi

          echo IMAGE_ID="$IMAGE_ID"
          echo VERSION="$VERSION"

          docker tag "$IMAGE_NAME" "$IMAGE_ID":"$VERSION"
          docker push "$IMAGE_ID":"$VERSION"
