name: Tag

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release-gem.outputs.pushed-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Push tag
        id: release-gem
        run: |
          tagname="1.29"
          git config user.name "$(git log -1 --pretty=format:%an)"
          git config user.email "$(git log -1 --pretty=format:%ae)"
          git tag -a -m "Gem release $tagname" "$tagname"
          git push origin "$tagname"

          echo "pushed-version=1.29" >> "$GITHUB_OUTPUT"
  trigger-ghcr-push:
    name: Trigger container push to GHCR
    runs-on: ubuntu-latest
    needs: release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh workflow --repo ${{ github.repository }} run "Push to Github Container Registry" -f version=${{needs.release.outputs.version}}
